### ISSUE TITLE
Error, no tests found on Windows

### ISSUE THREAD

**Issue by steffsommer** [andy-bell101/neotest-java#7]
# error/bug explanation

When executing tests on Windows in a minimal project
- Gradle 8.2.1
- build.gradle.kts build file

Neotest says there are no tests available with the following error message:

> [...]
> What went wrong:
> Execution failed for task ':test'.
> No tests found for given includes: ['com.steff.demo.DemoApplicationTests.*'](--tests filter)
> [...]

The include Filter is correct, so there is nothing suspicious. Then I looked at the Neotest log and the generated command looks  also correct:

> [...]
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:239 | Test spec = {
>  command = "gradle test --tests 'com.steff.demo.DemoApplicationTests.*'",
>  context = {},
>  cwd = "C:\\Users\\Steff\\code\\java_gradle_demo"
>}
> [...]

`cwd` and `command` are both correct. I can even execute the command in PowerShell and it works.
Not sure if this is a problem from your adapter or from Neotest.

[Reproducer Repo](https://github.com/steffsommer/java_gradle_demo), but only works when [this issue](https://github.com/andy-bell101/neotest-java/issues/6) is resolved, because it contains a `build.gradle.kts` file.

# full log

<details>

> INFO | 2023-08-22T11:09:00Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:33 | Starting child process
> INFO | 2023-08-22T11:09:00Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:36 | Parent address: localhost:50386
> INFO | 2023-08-22T11:09:00Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:42 | Starting child process with command: C:\Program Files\Neovim\bin\nvim.exe --embed --headless
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/config/init.lua:362 | Configuration complete
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/config/init.lua:363 | User config {
>   adapters = { {
>       build_position = <function 1>,
>       build_spec = <function 2>,
>       discover_positions = <function 3>,
>       is_test_file = <function 4>,
>       name = "neotest-java",
>       position_id = <function 5>,
>       results = <function 6>,
>       root = <function 7>,
>       <metatable> = {
>         __call = <function 8>
>       }
>     } },
>   benchmark = {
>     enabled = true
>   },
>   consumers = {},
>   default_strategy = "integrated",
>   diagnostic = {
>     enabled = true,
>     severity = 1
>   },
>   discovery = {
>     concurrent = 20,
>     enabled = true
>   },
>   floating = {
>     border = "rounded",
>     max_height = 0.6,
>     max_width = 0.6,
>     options = {}
>   },
>   highlights = {
>     adapter_name = "NeotestAdapterName",
>     border = "NeotestBorder",
>     dir = "NeotestDir",
>     expand_marker = "NeotestExpandMarker",
>     failed = "NeotestFailed",
>     file = "NeotestFile",
>     focused = "NeotestFocused",
>     indent = "NeotestIndent",
>     marked = "NeotestMarked",
>     namespace = "NeotestNamespace",
>     passed = "NeotestPassed",
>     running = "NeotestRunning",
>     select_win = "NeotestWinSelect",
>     skipped = "NeotestSkipped",
>     target = "NeotestTarget",
>     test = "NeotestTest",
>     unknown = "NeotestUnknown",
>     watching = "NeotestWatching"
>   },
>   icons = {
>     child_indent = "│",
>     child_prefix = "├",
>     collapsed = "─",
>     expanded = "╮",
>     failed = "",
>     final_child_indent = " ",
>     final_child_prefix = "╰",
>     non_collapsible = "─",
>     passed = "",
>     running = "",
>     running_animated = { "/", "|", "\\", "-", "/", "|", "\\", "-" },
>     skipped = "",
>     unknown = "",
>     watching = ""
>   },
>   jump = {
>     enabled = true
>   },
>   log_level = 0,
>   output = {
>     enabled = true,
>     open_on_run = "short"
>   },
>   output_panel = {
>     enabled = true,
>     open = "botright split | resize 15"
>   },
>   projects = {
>     <metatable> = {
>       __index = <function 9>
>     }
>   },
>   quickfix = {
>     enabled = true,
>     open = false
>   },
>   run = {
>     enabled = true
>   },
>   running = {
>     concurrent = true
>   },
>   state = {
>     enabled = true
>   },
>   status = {
>     enabled = true,
>     signs = true,
>     virtual_text = false
>   },
>   strategies = {
>     integrated = {
>       height = 40,
>       width = 120
>     }
>   },
>   summary = {
>     animated = true,
>     enabled = true,
>     expand_errors = true,
>     follow = true,
>     mappings = {
>       attach = "a",
>       clear_marked = "M",
>       clear_target = "T",
>       debug = "d",
>       debug_marked = "D",
>       expand = { "<CR>", "<2-LeftMouse>" },
>       expand_all = "e",
>       jumpto = "i",
>       mark = "m",
>       next_failed = "J",
>       output = "o",
>       prev_failed = "K",
>       run = "r",
>       run_marked = "R",
>       short = "O",
>       stop = "u",
>       target = "t",
>       watch = "w"
>     },
>     open = "botright vsplit | vertical resize 50"
>   },
>   watch = {
>     enabled = true,
>     symbol_queries = {
>       elixir = <function 10>,
>       lua = '        ;query\n        ;Captures module names in require calls\n        (function_call\n          name: ((identifier) @function (#eq? @function "require"))\n          arguments: (arguments (string) @symbol))\n      ',
>       python = "        ;query\n        ;Captures imports and modules they're imported from\n        (import_from_statement (_ (identifier) @symbol))\n        (import_statement (_ (identifier) @symbol))\n      "
>     }
>   }
> }
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:84 | CHILD | Connected to parent instance
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:380 | Initialising client
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting starting event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event starting
> INFO | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/adapters/init.lua:18 | Found 1 adapters for directory C:\Users\Steff\code\java_gradle_demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/adapters/init.lua:19 | Adapters: { {
>     adapter = {
>       build_position = <function 1>,
>       build_spec = <function 2>,
>       discover_positions = <function 3>,
>       is_test_file = <function 4>,
>       name = "neotest-java",
>       position_id = <function 5>,
>       results = <function 6>,
>       root = <function 7>,
>       <metatable> = {
>         __call = <function 8>
>       }
>     },
>     root = "C:\\Users\\Steff\\code\\java_gradle_demo"
>   } }
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:281 | Searching C:\Users\Steff\code\java_gradle_demo for test files
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: gradle
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: gradle\wrapper
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\tmp
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\test-results
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\resources
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\test\java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main\resources
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main\java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\tmp\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\tmp\compileTestJava
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\tmp\compileJava
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\test-results\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\resources\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\test\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\main\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\test\java\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main\java\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\test-results\test\binary
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\headers
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\annotationProcessor
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\test\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\main\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\test\java\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main\java\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests\test\packages
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests\test\js
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests\test\css
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\reports\tests\test\classes
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\headers\java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\annotationProcessor\java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\test\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\main\com
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\test\com\steff\demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: bin\main\com\steff\demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\test\java\com\steff\demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: src\main\java\com\steff\demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\headers\java\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\headers\java\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\annotationProcessor\java\test
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\generated\sources\annotationProcessor\java\main
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\test\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\main\com\steff
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\test\com\steff\demo
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/find.lua:26 | Scanning directory: build\classes\java\main\com\steff\demo
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:141 | Searching file C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java for test positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:138 | Waiting for result 1
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:151 | CHILD | Received remote call 1 <function 1>
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/init.lua:22 | CHILD | Reading file: C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:89 | Result registed for callback 1
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:297 | Found { {
>     id = "C:\\Users\\Steff\\code\\java_gradle_demo",
>     name = "java_gradle_demo",
>     path = "C:\\Users\\Steff\\code\\java_gradle_demo",
>     type = "dir"
>   }, { {
>       id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src",
>       name = "src",
>       path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src",
>       type = "dir"
>     }, { {
>         id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test",
>         name = "test",
>         path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test",
>         type = "dir"
>       }, { {
>           id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java",
>           name = "java",
>           path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java",
>           type = "dir"
>         }, { {
>             id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com",
>             name = "com",
>             path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com",
>             type = "dir"
>           }, { {
>               id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff",
>               name = "steff",
>               path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff",
>               type = "dir"
>             }, { {
>                 id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo",
>                 name = "demo",
>                 path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo",
>                 type = "dir"
>               }, { {
>                   id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>                   name = "DemoApplicationTests.java",
>                   path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>                   type = "file"
>                 } } } } } } } } }
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:54 | New positions at ID C:\Users\Steff\code\java_gradle_demo
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting discover_positions event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener state for event discover_positions
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:327 | Discovering files with 20 workers
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:301 | Parsing C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:141 | Searching file C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java for test positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:138 | Waiting for result 2
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:151 | CHILD | Received remote call 2 <function 1>
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/init.lua:22 | CHILD | Reading file: C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest/lua/neotest/lib/subprocess.lua:89 | Result registed for callback 2
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:307 | Found { {
>     id = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>     name = "DemoApplicationTests.java",
>     path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>     range = { 0, 0, 16, 0 },
>     type = "file"
>   }, { {
>       id = "com.steff.demo.DemoApplicationTests",
>       name = "com.steff.demo.DemoApplicationTests",
>       path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>       range = { 7, 0, 15, 1 },
>       type = "namespace"
>     }, { {
>         id = "com.steff.demo.DemoApplicationTests.contextLoads",
>         name = "contextLoads",
>         path = "C:\\Users\\Steff\\code\\java_gradle_demo\\src\\test\\java\\com\\steff\\demo\\DemoApplicationTests.java",
>         range = { 11, 21, 13, 2 },
>         type = "test"
>       } } } }
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:54 | New positions at ID C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting discover_positions event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event discover_positions
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener state for event discover_positions
> INFO | 2023-08-22T11:09:01Z+0200 | ...te\pack\packer\start\neotest/lua/neotest/client/init.lua:481 | Initialisation finished in 0.04 seconds
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting test_file_focused event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event test_file_focused
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event test_file_focused
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event test_file_focused
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting started event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event started
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:85 | Setting positions to running com.steff.demo.DemoApplicationTests
> TRACE | 2023-08-22T11:09:01Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:86 | { "com.steff.demo.DemoApplicationTests", "com.steff.demo.DemoApplicationTests.contextLoads" }
> INFO | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting run event
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event run
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event run
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event run
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener state for event run
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:215 | Building test spec
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:63 | Found C:\Users\Steff\code\java_gradle_demo\build.gradle.kts, using gradle runner
> INFO | 2023-08-22T11:09:01Z+0200 | ...pack\packer\start\neotest-java/lua/neotest-java/init.lua:239 | Test spec = {
>   command = "gradle test --tests 'com.steff.demo.DemoApplicationTests.*'",
>   context = {},
>   cwd = "C:\\Users\\Steff\\code\\java_gradle_demo"
> }
> INFO | 2023-08-22T11:09:01Z+0200 | ...ker\start\neotest/lua/neotest/client/strategies/init.lua:34 | Starting process neotest-java:C:\Users\Steff\code\java_gradle_demo-com.steff.demo.DemoApplicationTests with strategy integrated
> DEBUG | 2023-08-22T11:09:01Z+0200 | ...ker\start\neotest/lua/neotest/client/strategies/init.lua:35 | Strategy spec {
>   command = "gradle test --tests 'com.steff.demo.DemoApplicationTests.*'",
>   context = {},
>   cwd = "C:\\Users\\Steff\\code\\java_gradle_demo",
>   strategy = {
>     height = 40,
>     width = 120
>   }
> }
> INFO | 2023-08-22T11:09:09Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting test_focused event
> DEBUG | 2023-08-22T11:09:09Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event test_focused
> INFO | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting test_focused event
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event test_focused
> INFO | 2023-08-22T11:09:14Z+0200 | ...ker\start\neotest/lua/neotest/client/strategies/init.lua:54 | Process for position neotest-java:C:\Users\Steff\code\java_gradle_demo-com.steff.demo.DemoApplicationTests exited with code 1
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...ker\start\neotest/lua/neotest/client/strategies/init.lua:56 | Output of process  C:\Users\Steff\AppData\Local\Temp\nvim.0\rQ0PCh\0
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:70 | New results for adapter neotest-java:C:\Users\Steff\code\java_gradle_demo
> TRACE | 2023-08-22T11:09:14Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:71 | {
>   ["com.steff.demo.DemoApplicationTests"] = {
>     errors = {},
>     output = "C:\\Users\\Steff\\AppData\\Local\\Temp\\nvim.0\\rQ0PCh\\0",
>     status = "failed"
>   },
>   ["com.steff.demo.DemoApplicationTests.contextLoads"] = {
>     errors = {},
>     output = "C:\\Users\\Steff\\AppData\\Local\\Temp\\nvim.0\\rQ0PCh\\0",
>     status = "failed"
>   }
> }
> INFO | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting results event
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener output for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener quickfix for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:70 | New results for adapter neotest-java:C:\Users\Steff\code\java_gradle_demo
> TRACE | 2023-08-22T11:09:14Z+0200 | ...k\packer\start\neotest/lua/neotest/client/state/init.lua:71 | {
>   ["com.steff.demo.DemoApplicationTests"] = {
>     errors = {},
>     output = "C:\\Users\\Steff\\AppData\\Local\\Temp\\nvim.0\\rQ0PCh\\0",
>     status = "failed"
>   },
>   ["com.steff.demo.DemoApplicationTests.contextLoads"] = {
>     errors = {},
>     output = "C:\\Users\\Steff\\AppData\\Local\\Temp\\nvim.0\\rQ0PCh\\0",
>     status = "failed"
>   }
> }
> INFO | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting results event
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener output for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener quickfix for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener diagnostic for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...acker\start\neotest/lua/neotest/consumers/diagnostic.lua:55 | Setting diagnostics for C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java {}
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener output_panel for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener state for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...acker\start\neotest/lua/neotest/consumers/diagnostic.lua:55 | Setting diagnostics for C:\Users\Steff\code\java_gradle_demo\src\test\java\com\steff\demo\DemoApplicationTests.java {}
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener status for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener output_panel for event results
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/init.lua:22 | Reading file: C:\Users\Steff\AppData\Local\Temp\nvim.0\rQ0PCh\0
> DEBUG | 2023-08-22T11:09:14Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener state for event results
> INFO | 2023-08-22T11:09:18Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting test_focused event
> DEBUG | 2023-08-22T11:09:18Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event test_focused
> DEBUG | 2023-08-22T11:09:21Z+0200 | ...\pack\packer\start\neotest/lua/neotest/lib/file/init.lua:22 | Reading file: C:\Users\Steff\AppData\Local\Temp\nvim.0\rQ0PCh\0
> INFO | 2023-08-22T11:09:25Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:48 | Emitting test_focused event
> DEBUG | 2023-08-22T11:09:25Z+0200 | ...\packer\start\neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event test_focused

</details>

**Comment by andy-bell101** [comment]
I don't have a windows machine to test this on. Hopefully one of the latest commits should fix this now that `gradlew` is used correctly. If not I'll see about setting up a VM or something

**Comment by steffsommer** [comment]
Thanks for responding so fast. Unfortunately the error persists despite the latest commits. I would like to try debugging as well, although I haven't developed for Neovim before. Could you please give me some pointers on how to set up my environment or links to documentation?

**Comment by andy-bell101** [comment]
Aside from treesitter and the lua-ls language server, this plugin is useful

https://github.com/folke/neodev.nvim

Otherwise I didn't have any tooling or environments set up. It might be worth asking on the subreddit to get some recommendations from people who do this more often

**Comment by steffsommer** [comment]
I have found the issue and it is indeed inside neotest-java.

The generated command from neotest-java looks like this: 

`C:\\Users\\Steff\\code\\java_gradle_demo\\gradlew.bat test --tests 'com.steff.demo.DemoApplicationTests.*'`

Neotest probably executes the command inside cmd and from what I've read it's often hard to tell what `'` quoted strings do in cmd ([It seems they should be avoided](https://stackoverflow.com/questions/24173825/what-does-single-quoting-do-in-windows-batch-files)). Anyways, it works with double quotes:

`C:\\Users\\Steff\\code\\java_gradle_demo\\gradlew.bat test --tests "com.steff.demo.DemoApplicationTests.*"`

At first I did not notice that, because powershell quoting behaves like bash, contrary to cmd. I'm not sure whether the general quoting style could be using `"`. Maybe the `*` character gets expanded on Linux then and yields different results, but I would give checking that out back into your hands.

**Comment by andy-bell101** [comment]
I don't think the * is expanded in bash, given it's in quotes. And I assume neotest uses bash to run its commands. I'll make the change when I get home and see if I can set up GitHub actions to run on different OS's

**Comment by andy-bell101** [comment]
Ok I've switched to using " characters instead of '. Hopefully that fixes things
